# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed]
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
 # workflow_dispatch:
env:
  name: Universal Name #name that every job can have access
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#All the JOBS are listed below
jobs:
  # This workflow contains a single job called "build"
  build: #Job1
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      name: Anderson #redefine the name

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, $name!
          echo Actor: ${{ github.actor }}
          echo Committed By:: ${{ github.event.commits[0].author.name }}
          

  dump: #Job3
      runs-on: ubuntu-latest
      steps:
        -env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"


  pull_requests_only: #Job2
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #if you make a pull request the job will run
    if: github.event_name == 'pull_request'
    needs: build #the job named "build" needs to finish first for this to be executed

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Hi, $name.
